/** Judge / integrator-facing checklist of capabilities (mirrors shipped routes). */
export function buildFeatureCatalog(): { service: string; features: string[] } {
  return {
    service: "StablePilot",
    features: [
      "Four-layer governance pipeline with z-score drift statistics",
      "Autonomous vs human approval modes for WDK transfers",
      "Persisted run history + CSV/JSON export",
      "Treasury health score + runway estimate",
      "Simulation mode + stress lab + portfolio satellite vaults (sim)",
      "Circuit breaker kill switch + daily USDT spend cap",
      "Audit bundle + optional HMAC + policy fingerprint",
      "SSE live activity stream",
      "Optional OpenAI-compatible executive explain (facts-only)",
      "Agent dry-run preview + multi-balance compare",
      "Judge briefing JSON + print-friendly page",
      "Block explorer deep links for real tx hashes",
      "Prometheus /metrics scrape endpoint",
      "Single-call treasury summary rollup",
      "Runtime agent interval override (bounded)",
      "Run analytics by outcome (24h / 7d / all)",
      "Live z-stats snapshot endpoint",
      "Webhook test ping",
      "OpenAPI 3 machine-readable spec",
      "Maintenance freeze (evaluate policy, skip execution)",
      "Batch agent runs (bounded)",
      "Activity report + transfer ledger API",
      "Simulated demo scenarios (one-shot balances)",
      "Readiness probe with wallet dependency check",
      "Daily budget counter reset (sim or ops token)",
      "Governance counters from history",
      "Wallet snapshot ring buffer (recent reads)",
      "Compliance export bundle (audit + fingerprint + summary)",
      "Pipeline layer documentation JSON",
      "Utility echo + SHA-256 hash for tool testing",
      "Configurable CORS + X-Request-Id propagation",
      "Server clock endpoint",
      "Ops activity feed clear (sim or ops token)",
      "Treasury Stability Index (TSI) — composite 0–100 score",
      "Policy matrix — compare all presets without changing runtime",
      "Attestation snapshot — root hash binding fingerprint to audit",
      "Innovation manifest — judge-facing differentiator copy",
      "Scenario chain lab — multi shock script in one API call",
      "Dual-wallet snapshots — optional secondary read-only WDK wallet",
      "Signed outbound webhooks (HMAC) via WEBHOOK_HMAC_SECRET",
      "Engage badges + UTC activity streak from run history",
      "Risk radar — five 0–100 axes for chart demos",
      "Runway what-if — linear days-to-min given daily burn",
      "Compare any two runIds side-by-side",
      "Policy diff — numeric delta between any two presets",
      "Balance heatmap — hourly UTC averages for viz",
      "Webhook event catalog for integrators",
      "Proof-of-run SHA-256 for a single runId",
      "DevTools curl bundle (copy-paste shell)",
      "Meta: changelog, feature flags, live request stats",
      "Bot-style POST /integrations/command (Slack/Discord-style)",
      "Treasury goal tracker with progress percent",
      "Governance preview-impact before approving an amount",
      "Public /public/status card for embeds",
      "Judge trust score (separate composite from TSI)",
      "Markdown executive one-pager (no LLM)",
      "GET /sim/presets — 13+ named simulation scenarios"
    ]
  };
}
